services:
  webapp:
    platform: "linux/amd64"
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    env_file:
      - ./webapp/.env
    environment:
      - ARKIVGPT_URL=http://host.docker.internal:80/api
      - PLANPRAT_URL=http://host.docker.internal:8000/plan-prat/
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    platform: "linux/amd64"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
